import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Il Cuore di Loco",
  description: "Generated by create next app",
  icons: "/logo_trans.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body className="flex flex-col justify-between bg-accent min-w-[240px] min-h-screen">
        <Header />
        <main className="flex flex-1 flex-col items-center justify-center min-w-screen container h-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
